name: pytest CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      TEST_DIR: app/test/
      PYTHON_VERSION: 3.8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest-cov

      - name: Test with pytest
        working-directory: ./${{ env.TEST_DIR }}
        run: |
          python -m pytest -v

      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=app ./${{ env.TEST_DIR }} > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
