name: pytest CI

on:
  pull_request:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      TEST_DIR: app/test/
      PYTHON_VERSION: 3.8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app:
              - 'app/**'
          base: main
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Test with pytest
        if: steps.changes.outputs.app == 'true'
        working-directory: ./${{ env.TEST_DIR }}
        run: |
          python -m pytest -v

      - name: Coverage comment
        id: coverage_comment
        uses: ewjoachim/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
